name = "Romberg"
uuid = "ff01fdde-158c-414c-948f-c94b4a236685"
authors = ["Forrest Gasdia", "Steven G. Johnson"]
version = "0.2.0"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Richardson = "708f8203-808e-40c0-ba2d-98a6953ed40d"

[compat]
julia = "1"
Primes = "0.5"
Richardson = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
