name = "Romberg"
uuid = "ff01fdde-158c-414c-948f-c94b4a236685"
authors = ["Forrest Gasdia"]
version = "0.1.0"

[deps]
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"

[compat]
julia = "1"
Trapz = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"

[targets]
test = ["Test", "Trapz"]
